name: Lint
on:
    push:

jobs:
    lint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: User Node.js LTS
              uses: actions/setup-node@v2

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn run lint

            - name: Linter Failed
              if: ${{ failure() }}
              uses: actions/github-script@v5
              with:
                  script: |
                      const { pullRequestData: data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                              owner: context.repo.owner,
                              repo: context.repo.repo,
                              commit_sha: context.payload.after
                          })

                        if(pullRequestData[0]){
                           await github.rest.issues.createComment({
                                issue_number: pullRequestData[0].number,
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                body: `### 🚨  Linter failed`
                            })
                        } else {
                            throw new Error('Pull request data not found')
                        }
