name: Deploy

on:
    push:
        branches:
            - 'master'
    workflow_run:
        workflows:
            - 'Lint'
        types:
            - 'completed'

jobs:
    deploy:
        environment: Production
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: User Node.js LTS
              uses: actions/setup-node@v2

            - name: Install Vercel CLI
              run: yarn global add vercel@canary

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn run build

            - name: Trigger Production Deployment
              run: vercel deploy -y --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

            - name: Deployment Failure
              if: ${{ failure() }}
              uses: actions/github-script@v5
              with:
                  script: |
                      const { pullRequestData: data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            commit_sha: context.payload.after
                        })

                      // ! TODO: send notification either on slack or on discord

                      if(pullRequestData[0]){
                         await github.rest.issues.createComment({
                              issue_number,
                              owner: context.repo.owner,
                              repo: context.repo.repo,
                              body: `#### ❌ Deployment failed:
                      `
                          })
                      } else {
                      throw new Error('Pull request data not found')
                      }
